<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DPSinfra" Version="2.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DPS_Lib\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DBConnection">
      <HintPath>DPS_Lib\DBConnection.dll</HintPath>
    </Reference>
    <Reference Include="DpsLibs">
      <HintPath>DPS_Lib\DpsLibs.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
